service: culqi

useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x

functions:
    token:
        handler: src/functions/token.handler
        events:
            - httpApi: POST /tokens
    card:
        handler: src/functions/card.handler
        events:
            - httpApi: GET /cards

plugins:
    - serverless-offline
    - serverless-esbuild
